# 矩阵、数组的基本操作

In [2]:
import numpy as np
from numpy import *  # 调用numpy模块中所有模块

## 矩阵的创建 

In [7]:
mat([[-2, 3, 4], [4, 9, -8], [2, 5, 6]])  # 创建多行矩阵

matrix([[-2,  3,  4],
        [ 4,  9, -8],
        [ 2,  5,  6]])

In [11]:
mat([1, 2, 3])

matrix([[1, 2, 3]])

In [12]:
mat(zeros((3, 3)))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
mat(ones((2, 4)))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
mat(random.rand(2, 3))

matrix([[0.09150482, 0.53065038, 0.57518391],
        [0.13214059, 0.89559463, 0.97678178]])

In [25]:
mat(diag([1, 2, 3, 4]))

matrix([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])

In [29]:
mat(eye(4, 4, dtype="int"))  # eye输出的矩阵的元素本身是float类型

matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

## matrix和array的区别 
Matrix类型继承于ndarray类型，因此含有ndarray的所有数据属性和方法。Matrix类型与ndarray类型有六个重要的不同点，当你当Matrix对象当arrays操作时，这些不同点会导致非预期的结果。
1）Matrix对象可以使用一个Matlab风格的字符串来创建，也就是一个以空格分隔列，以分号分隔行的字符串。
2）Matrix对象总是二维的。这包含有深远的影响，比如m.ravel()的返回值是二维的，成员选择的返回值也是二维的，因此序列的行为与array会有本质的不同。
3）Matrix类型的乘法覆盖了array的乘法，使用的是矩阵的乘法运算。当你接收矩阵的返回值的时候，确保你已经理解这些函数的含义。特别地，事实上函数asanyarray(m)会返回一个matrix，如果m是一个matrix。
4）Matrix类型的幂运算也覆盖了之前的幂运算，使用矩阵的幂。根据这个事实，再提醒一下，如果使用一个矩阵的幂作为参数调用asanarray(…)跟上面的相同。
5）矩阵默认的array_priority是10.0，因而ndarray和matrix对象混合的运算总是返回矩阵。
6）矩阵有几个特有的属性使得计算更加容易，这些属性有：

(a) .T －－ 返回自身的转置

(b) .H －－ 返回自身的共轭转置

(c) .I －－ 返回自身的逆矩阵

(d) .A －－ 返回自身数据的2维数组的一个视图（没有做任何的拷贝）
Matrix类是ndarray的一个Python子类，你也可以学习这个实现来构造自己的ndarray子类。Matrix对象也可以使用其它的Matrix对象，字符串，或者其它的可以转换为一个ndarray的参数来构造。另外，在NumPy里，“mat”是“matrix”的一个别名。

In [18]:
np.arange(2,10).reshape((2, 4))  # a

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [21]:
mat(np.arange(2,10).reshape((2, 4)))

matrix([[2, 3, 4, 5],
        [6, 7, 8, 9]])

In [7]:
# 不要小瞧这一个括号的区别，对很多操作有影响
# 对于相同的命令，用np就是array类型，用mat就是matrix类型
a = np.arange(2,10).reshape((2, 4))
b = mat(np.arange(2,10).reshape((2, 4)))
c = mat(np.random.randint(2, 9, size=(2, 4))) 
print(a[0, :])
print(b[0, :])
print(" "*20)
print(c)

[2 3 4 5]
[[2 3 4 5]]
                    
[[8 5 3 3]
 [7 7 3 4]]


In [8]:
a.ravel()

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b.ravel()

matrix([[2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
b.A

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [3]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [4]:
np.linspace(0, 20, 10)  # 和arange命令不同，包括截止点，而且，这个10表示将0~20等分10份

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## 矩阵运算 

In [9]:
mat([[-2, 3, 4], [4, 9, -8], [2, 5, 6]]) * mat([[-2, 3, 4], [4, 9, -8], [2, 5, 6]]) 

matrix([[  24,   41,   -8],
        [  12,   53, -104],
        [  28,   81,    4]])

In [30]:
a + b  # matrix类型和array可以进行一系列运算，并且强制转换为matrix类型

matrix([[ 4,  6,  8, 10],
        [12, 14, 16, 18]])

In [32]:
a + c

matrix([[ 8, 10, 10, 12],
        [ 8, 13, 15, 11]])

In [33]:
a - c 

matrix([[-4, -4, -2, -2],
        [ 4,  1,  1,  7]])

In [34]:
a * 3

array([[ 6,  9, 12, 15],
       [18, 21, 24, 27]])

In [35]:
multiply(a, c)  # 相当于数乘，对应位置元素相乘

matrix([[12, 21, 24, 35],
        [12, 42, 56, 18]])

In [36]:
multiply(a, [1, 2, 3, 4])

array([[ 2,  6, 12, 20],
       [ 6, 14, 24, 36]])

In [38]:
dot(a, c.T)  # 正常矩阵相乘，注意a的列数要等于的行数

matrix([[ 92,  60],
        [196, 128]])

In [43]:
a * c.T  # 结果同上

matrix([[ 92,  60],
        [196, 128]])

In [39]:
a.T  # a的转置

array([[2, 6],
       [3, 7],
       [4, 8],
       [5, 9]])

In [41]:
c.I  # c矩阵的逆，a矩阵不存在逆矩阵

matrix([[ 0.09110512, -0.08625337],
        [-0.00242588,  0.06738544],
        [-0.05714286,  0.14285714],
        [ 0.11617251, -0.11590296]])

In [44]:
a.sum(axis=0)  # 计算每一列的和

array([ 8, 10, 12, 14])

In [54]:
a.sum(axis=1)  # 计算每一行的和

array([14, 30])

In [38]:
np.max(a, axis=0)  # 每一列的最大值

array([6, 7, 8, 9])

In [39]:
a.argmax(axis=1)  # 每一行最大值对应的索引

array([3, 3], dtype=int64)

In [43]:
np.median(b, axis=0)  # 统计各中位数

matrix([[4., 5., 6., 7.]])

In [44]:
np.mean(a, axis=1)  # 统计各行的算术平均值

array([3.5, 7.5])

In [45]:
np.average(c, axis=1)  # 统计各行的加权平均值

matrix([[4.75],
        [5.25]])

In [46]:
np.var(c, axis=1)  # 统计各行的方差

matrix([[4.1875],
        [3.1875]])

In [47]:
np.std(c, axis=1)  # 统计各行的标准偏差

matrix([[2.04633819],
        [1.78535711]])

## 数组、矩阵的合并 

In [33]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [34]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [35]:
z = np.array([666, 666, 666])

In [36]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [41]:
A = np.arange(6).reshape(2, 3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
np.concatenate([A, A])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [43]:
np.concatenate([A, A], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [55]:
vstack((a, c))  # 按列合并

matrix([[2, 3, 4, 5],
        [6, 7, 8, 9],
        [4, 3, 7, 6],
        [2, 7, 2, 6]])

In [56]:
hstack((a, c))  # 按列合并

matrix([[2, 3, 4, 5, 4, 3, 7, 6],
        [6, 7, 8, 9, 2, 7, 2, 6]])

## 矩阵、数组的分割

In [44]:
x  = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
x1, x2, x3 = np.split(x, [3, 7])  # 将其分割为三分，分割索引分别为3和7

In [46]:
x1

array([0, 1, 2])

In [47]:
x2

array([3, 4, 5, 6])

In [48]:
x1, x2 = np.split(x, [5])  # 即使分割成两份也要传入列表

In [49]:
x1

array([0, 1, 2, 3, 4])

In [51]:
A = np.arange(16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
A1, A2 = np.split(A, [3])  # 同样可以用vsplit/hsplit命令实现相同功能

In [56]:
A1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
A2

array([[12, 13, 14, 15]])

In [58]:
A1, A2 = np.split(A, [3] ,axis=1)

In [59]:
A1

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

## 矩阵、数组、列表的转换 

In [20]:
a.tolist()

[[2, 3, 4, 5], [6, 7, 8, 9]]

In [59]:
array(b)

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [60]:
mat(a)

matrix([[2, 3, 4, 5],
        [6, 7, 8, 9]])

## 多维数据转换为一维列表

In [49]:
from itertools import chain
list(chain.from_iterable(a))

[2, 3, 4, 5, 6, 7, 8, 9]

In [51]:
a

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [55]:
mat([[4, 2, 3],[5, 9, 1],[7, 8, 9]])
# from tkinter import _flatten  # 这种方法好像用不了了
# _flatten(t)

matrix([[4, 2, 3],
        [5, 9, 1],
        [7, 8, 9]])

## numpy  linalg模块 
numpy.linalg模块包含线性代数的函数。使用这个模块，可以计算逆矩阵、求特征值、解线性方程组以及求解行列式等。

In [4]:
# 求解矩阵的逆
d = mat(np.random.randint(2, 10, size=(4, 4)))
np.linalg.inv(d)  # 好像这个模块要求矩阵必须是方阵且可逆

matrix([[-0.3908046 ,  0.47126437,  0.37931034, -0.48850575],
        [-0.25287356,  0.54022989,  0.06896552, -0.31609195],
        [ 0.17241379, -0.4137931 , -0.13793103,  0.46551724],
        [ 0.85057471, -0.90804598, -0.4137931 ,  0.56321839]])

In [5]:
d.I  # 这个方法可以求解非满秩矩阵的逆

matrix([[-0.3908046 ,  0.47126437,  0.37931034, -0.48850575],
        [-0.25287356,  0.54022989,  0.06896552, -0.31609195],
        [ 0.17241379, -0.4137931 , -0.13793103,  0.46551724],
        [ 0.85057471, -0.90804598, -0.4137931 ,  0.56321839]])

In [27]:
np.linalg.pinv(mat([[4, 11, 14], [8, 7,-2]]))  # 求解的是广义逆矩阵，不要求矩阵一定是方阵

matrix([[-0.00555556,  0.07222222],
        [ 0.02222222,  0.04444444],
        [ 0.05555556, -0.05555556]])

In [18]:
# 求解线性方程组
# 注意这两种方式的区别，但是现在还不清楚具体分别用在什么情况
E = mat("1 -2 1; 0 2 -8; -4 5 9")
e = mat("0; 8; -9")  # 用这种方式，e必须写成列向量的形式
f = np.array([0, 8, -9])  # 用这种方式，f必须写成行向量的形式
print(np.linalg.solve(E, e))  # 输出是一个二维的
print(np.linalg.solve(E, f))  # 输出是一个一维的

[[29.]
 [16.]
 [ 3.]]
[29. 16.  3.]


In [26]:
# 特征值和特征向量
# 特征值（eigenvalue）即方程 Ax = ax 成立时，a的值。其中，A 是一个二维矩阵，x 是一个
#一维向量。特征向量（eigenvector）是关于特征值的向量
# numpy.linalg模块中，eigvals函数可以计算矩阵的特征值，而eig函数可以返回一个包含特征值
# 和对应的特征向量的元组
C = mat([[3, -2], [1, 0]])
c0 = np.linalg.eigvals(C)
print(c0)
c1,c2 = np.linalg.eig(C)
print(c1)
print(c2)

[2. 1.]
[2. 1.]
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [31]:
# 计算矩阵的行列式
np.linalg.det(mat([[3, 4], [5, 6]]))

-1.9999999999999971

In [36]:
# 矩阵分解
D = mat("4 11 14;8 7 -2")
U,Sigma,V = np.linalg.svd(D, full_matrices=False)
print("U:", U)
print("Sigma:", Sigma)
print("V:", V)
print(U * diag(Sigma) * V)

U: [[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]]
Sigma: [18.97366596  9.48683298]
V: [[-0.33333333 -0.66666667 -0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]
[[ 4. 11. 14.]
 [ 8.  7. -2.]]


In [37]:
# 范数
x = np.arange(0, 6).reshape(2, 3)
np.linalg.norm(x, ord=1)

7.0

## np中的random命令

In [6]:
np.random.randint(0, 10)  # 生成一个[0,10)之间的随机整数

2

In [7]:
np.random.randint(0, 10, 10)

array([0, 8, 6, 4, 9, 3, 0, 1, 2, 5])

In [8]:
np.random.randint(0, 10, (3, 5))

array([[5, 0, 6, 2, 2],
       [6, 1, 8, 0, 7],
       [4, 9, 1, 6, 2]])

In [9]:
np.random.randint(0, 10, (3, 5))  # 由于是随机矩阵，所以每次生成的不一样

array([[2, 4, 1, 9, 0],
       [4, 7, 3, 0, 5],
       [6, 6, 6, 7, 3]])

In [10]:
np.random.seed(78)
np.random.randint(0, 10, (3, 5))

array([[5, 6, 7, 8, 9],
       [6, 8, 4, 4, 3],
       [3, 8, 4, 4, 6]])

In [11]:
np.random.seed(78)
np.random.randint(0, 10, (3, 5))  # 指定随机种子，那么随机序列被确定，生成的随机矩阵一致

array([[5, 6, 7, 8, 9],
       [6, 8, 4, 4, 3],
       [3, 8, 4, 4, 6]])

In [12]:
np.random.random()  # 生成一个[0,1）之间的随机小数

0.4355720553564857

In [13]:
np.random.random(10)

array([0.95183206, 0.79763247, 0.67652832, 0.4762874 , 0.82396207,
       0.90718803, 0.45028405, 0.88519175, 0.65617443, 0.20514687])

In [14]:
np.random.normal()  # 生成一个符合标准正态分布的随机数

-0.26416530872340954

In [17]:
np.random.normal(10, 100)  # 生成一个均值为10，方差为100的正太分布随机数

91.59172238286256

In [18]:
np.random.normal(0, 1, (3, 5))

array([[ 1.96463345, -0.13243324,  0.88385034,  0.56368249,  1.52936154],
       [ 0.04089679, -0.68347145,  0.95375154, -0.80925708,  0.82061757],
       [-0.47126594,  1.00926378,  0.40051385, -0.93573561,  0.33253539]])

## numpy中一些基本属性（自己不太常用到的）

In [19]:
x = np.arange(15)

In [20]:
X = np.arange(15).reshape(3, 5)

In [21]:
x.ndim  # 这个命令可以查看当前数组的维度

1

In [22]:
X.ndim

2

In [23]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [24]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [25]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [27]:
subX1 = X[:2, :3].copy()
subX1

array([[100,   1,   2],
       [  5,   6,   7]])

In [28]:
subX1[0, 0] = 0
subX1

array([[0, 1, 2],
       [5, 6, 7]])

In [29]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [30]:
X.reshape(5, -1)  # 指定矩阵为5行，至于列数则由系统自己计算

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14]])

In [31]:
X.reshape(-1, 5)

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])